spring:
  application:
    name: pc-manager
  datasource:
    url: jdbc:mysql://localhost:3306/pcmanager?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always

server:
  port: 8081
  error:
    include-stacktrace: always
    include-exception: true
jwt.secret: "]0Rm-gn-=&_vm()un!:6Zl#jJqt9pgDY"